### PR TITLE
feat(input-textarea): add preview functionality

### PR DESCRIPTION
**Pull request by brc-dd**
https://deploy-preview-471--sefirot-story.netlify.app/story/stories-components-sinputtextarea-01-playground-story-vue?variantId=_default

We can probably leave `.prose ...` styles to be implemented at consumer-side because they largely will be common with the actual post rendering.

### CODE REVIEW

**Comment by kiaking** [comment]
@brc-dd 
Updated the style!

- Refactored css (put base stuff on top, custom at bottom)
- Adjusted `fill` option handling.

> We can probably leave .prose ... styles to be implemented at consumer-side because they largely will be common with the actual post rendering.

And I agree on this 👍 

Screenshot 2024-02-19 at 18 03 23

**Comment by kiaking** [comment]
Feel free to merge when you're ready. Nothing from my side anymore 🙌

**Comment by kiaking** [comment]
Oops wait, forgot about error state. Gonna fix it.

**Comment by kiaking** [comment]
OK, done.

**Comment by brc-dd** [comment]
LGTM

image

**Pull request merged**
