### PR TITLE
fix(input-select): stylings not applied correctly

### PR DESCRIPTION
**Pull request by kiaking**

### CODE REVIEW

**Comment by brc-dd** [comment]
On Windows it's looking like this:

image

Looks fine on mac though. On Windows IG it's applying the text color to options too.

**Comment by kiaking** [comment]
@brc-dd Thanks for checking! I think you're right, seems like `color` specified at `<select>` is inherited in `<option>` too, but not sure how to fix it 🤔 

So, it will look OK on `light` mode... right? Because then the text color should be black.

I've set `<option>` color to `color: initial`... It might help? Could you test it and see if it made any difference 👀 ?

**Comment by brc-dd** [comment]
> I've set <option> color to color: initial... It might help?

Yeah, it works!

**Comment by kiaking** [comment]
Yay! 🎉  Thanks for checking 👍 

Maybe for VitePress we might want to wrap `<Showcase>` with `vp-raw` 🤔

**Comment by brc-dd** [comment]
Yeah that or whyframe would work. 👍

**Pull request merged**
