### PR TITLE
feat(input-image): add `<SInputImage>` (#356)

### LINKED ISSUE #356: Add `<SInputImage>`
Add `<SInputImage>`. It's a component to handle image file with preview. Mostly used for things like profile photo upload.

Screenshot 2023-10-19 at 17 56 19

## Props

It's input component so it should inherit basic input props.

```ts
import { type Validatable } from 'sefirot/composables/Validation'

interface Props {
  // Base props to be passed down to `<SInputBase>`.
  // `:size` only controls the size of label in this component.
  size?: Size
  label?: string
  info?: string
  note?: string
  hideError?: boolean
  validation?: Validatable

  // In this component, `help` prop should not be passed to
  // `<SInputBase>`. It should be displayed below the
  // action buttons.
  help?: string

  // The shape of the image box.
  imageType?: 'rectangle' | 'circle' // Default: rectangle
  imageWidth?: number // Default: 96 (px)
  imageAspectRatio?: string // Default: '1 / 1'

  // Texts for action buttons.
  selectText?: string // Default: 'Upload image'
  deleteText?: string // Default: 'Delete image'

  // When it's `false`, do not show the delete button.
  nullable?: boolean // Default: true

  // When it's disabled, hide actions.
  disabled?: boolean // Default: false

  // The selected file. Same as other input,
  // `modelValue` takes precedence over `value`.
  //
  // String value is the `src` for the image. When showing the
  // component in update form, it would probably have the url
  // of the image.
  value?: File | string | null
  modelValue?: File | string | null
}

export type Size = 'mini' | 'small' | 'medium'
```

## Events

```ts
interface Events {
  // Emits when user selects a new file.
  // becomes `null` when user deletes the file.
  change: [value: File | null]
  'update:model-value': [value: File | null]
}
```

## Slots

- `#info`
  - Same as `:info`. When info prop and this slot are defined at the same time, this slot will take precedence.

## Styles

In order to have better control on image box size, make width of the box controllable via CSS variable. This variable should take precedence over `:width`.

```css
:root {
  --input-image-width: undefined;
}
```

---

Screenshot 2023-10-19 at 18 31 15

### PR DESCRIPTION
**Pull request by kiaking**
- require #367
- close #356

Add `<SInputImage>`. Pretty much followed all issue spec. Adjusted tiny wording of text.

Also, this PR contains new `useImageSrcFromFile` composable that can read image src from file.

- [x] Add docs

---

Screenshot 2023-11-02 at 20 48 58

### CODE REVIEW

**Review by brc-dd — APPROVED** [review]

**Comment by kiaking** [comment]
Oh sit lol

**Comment by kiaking** [comment]
Whaat...

**Comment by brc-dd** [comment]
I'll fix it separately, some ref issue probably.

**Comment by kiaking** [comment]
Gotcha. Thanks. Or maybe Histoire issue...?

**Comment by kiaking** [comment]
It's working for me on Histoire 🤔

**Comment by brc-dd** [comment]
#369, I was removing and uploading the same image 😅

**Comment by kiaking** [comment]
Ahhhh I see. And that I wasn't doing 😳 Nice catch.

**Pull request merged**
