### PR TITLE
feat(http): allow overriding fetch handler

### PR DESCRIPTION
**Pull request by brc-dd**
Bit of a breaking change:

```ts
// earlier -- Http.base = '/foo' -- now:

Http.config({
  baseURL: '/foo'
})
```

### CODE REVIEW

**Comment by kiaking** [comment]
I think it would be cooler if we can hide ofetch beneath Http 🤔  How about we add config method?

```ts
Http.config({
  base: '...',
  xsrfUrl: false
})
```

**Comment by brc-dd** [comment]
Ah, but need to replace ofetch entirely in nuxt. Maybe this: ?

```ts
Http.config({
  base: '...',
  xsrfUrl: false,
  $fetch: ... // when necessary?
})
```

**Comment by cuebit** [comment]
> Ah, but need to replace ofetch entirely in nuxt. Maybe this: ?
> 
> 
> 
> ```ts
> 
> Http.config({
> 
>   base: '...',
> 
>   xsrfUrl: false,
> 
>   $fetch: ... // when necessary?
> 
> })
> 
> ```

Yea this makes more sense. Probably ideal to allow passing an implementation than conditional operation where dependencies are concerned.

**Comment by brc-dd** [comment]
updated

**Review by kiaking — APPROVED** [review]
Nice! Looking smooth 👍

**Pull request merged**
