### PR TITLE
feat(validation): allow undersocre in domain name when validating email

### PR DESCRIPTION
**Pull request by kiaking**
There was a client who had email address that contains underscore in domain name. And seems like it is valid. So, updating email validation to allow unerscore.

### CODE REVIEW

**Comment by cuebit** [comment]
AFAIK underscore does not exist in a valid FQDN. Does the underscore in the client email reside within a different label i.e. foo_bar.example.com?

**Comment by kiaking** [comment]
Seems like underscore is valid as domain, and invalid as a host name. The client address was more like `john@abc_d.com`

**Comment by brc-dd** [comment]
Are they even able to use their email? Because according to RFC 5321 (SMTP) it's invalid.

**Comment by kiaking** [comment]
Seems like it. Our capitalist is actually communicating through that email address 🫠  So, we kinda have no choice 😆

**Comment by brc-dd** [comment]
ah ok, seems like there are 6 email standards 🫠 I think we can merge this for now, or just remove this (`return value.includes('@')`) and let laravel handle it.

**Comment by cuebit** [comment]
@brc-dd looks like you’ll have to fork tldts 😂

**Comment by brc-dd** [comment]
I'll port https://github.com/egulias/EmailValidator to JS some day 😅

**Comment by brc-dd** [comment]
Ok wait, but that package is also rejecting this 🤣 @kiaking Laravel will throw for this email.

**Comment by kiaking** [comment]
Ahhh... @brc-dd Well this fix will apply to non Laravel app so it's OK for now, but damn. We might have to create custom validation for Laravel then 🫠

**Pull request merged**
