### PR TITLE
build: update npm packages

### PR DESCRIPTION
**Pull request by cuebit**
Bumps the following deps:
```
@nuxt/types                       2.15.4      ❯  2.15.8
@nuxtjs/eslint-config-typescript  6.0.0       ❯  6.0.1
@types/body-scroll-lock           2.6.1       ❯  2.6.2
@types/jest                       26.0.23     ❯  26.0.24
@types/lodash-es                  4.17.4      ❯  4.17.5
@types/markdown-it                12.0.1      ❯  12.2.2
@types/prismjs                    1.16.5      ❯  1.16.6
@vue/composition-api              1.0.0-rc.6  ❯  1.2.3
@vue/test-utils                   1.1.3       ❯  1.2.2
codecov                           3.8.2       ❯  3.8.3
dayjs                             1.10.4      ❯  1.10.7
eslint                            7.26.0      ❯  7.32.0
markdown-it                       12.0.6      ❯  12.2.0
nuxt                              2.15.4      ❯  2.15.8
prismjs                           1.23.0      ❯  1.25.0
simplebar-vue                     1.6.3       ❯  1.6.8
ts-loader                         8.1.0       ❯  8.3.0
typescript                        4.2.4       ❯  4.4.3
v-calendar                        2.3.0       ❯  2.3.2
vue                               2.6.12      ❯  2.6.14
vue-router                        3.5.1       ❯  3.5.2
vue-server-renderer               2.6.12      ❯  2.6.14
vue-template-compiler             2.6.12      ❯  2.6.14
```

### CODE REVIEW

**Comment by cuebit** [comment]
As of [jsdom@16.4.0](https://github.com/jsdom/jsdom/releases/tag/16.4.0) native events such as `element.focus()` do nothing on disconnected elements. Triggering events such as `trigger('focus')` with `@vue/test-utils` require the component to be attached to the dom i.e. `attachTo: document.body`.

**Comment by cuebit** [comment]
Seems @nuxtjs/eslint-config-typescript is impacting import orders. Needs further investigation.

**Comment by kiaking** [comment]
@cuebit After running the `yarn install` and then `yarn serve`, I get these type errors. Is this happening to you?

```bash
 ERROR  ERROR in test/components/SDropdown.spec.ts:11:32                                                                                                                                                                                                                                                            12:19:16
TS2322: Type 'Wrapper<Vue, Element>' is not assignable to type 'Wrapper<object & Record<never, any> & Vue & { $data: Data; $props: Readonly<Partial<{ round: number; }> & Omit<{ options: Dropdown; round: number; } & {}, "round">>; $attrs: Data; } & ... 4 more ... & Omit<...>>'.
  Type 'Vue' is not assignable to type 'object & Record<never, any> & Vue & { $data: Data; $props: Readonly<Partial<{ round: number; }> & Omit<{ options: Dropdown; round: number; } & {}, "round">>; $attrs: Data; } & ... 5 more ... & Record<...>'.
    Type 'Vue' is not assignable to type '{ $data: Data; $props: Readonly<Partial<{ round: number; }> & Omit<{ options: Dropdown; round: number; } & {}, "round">>; $attrs: Data; }'.
      Types of property '$props' are incompatible.
        Property 'options' is missing in type 'Record<string, any>' but required in type 'Readonly<Partial<{ round: number; }> & Omit<{ options: Dropdown; round: number; } & {}, "round">>'.
     9 | describe('components/SDropdown', () => {
    10 |   beforeEach(() => {
  > 11 |     createWrapper = options => mount(SDropdown, {
       |                                ^^^^^^^^^^^^^^^^^^
  > 12 |       propsData: {
       | ^^^^^^^^^^^^^^^^^^
  > 13 |         options: useDropdown(options)
       | ^^^^^^^^^^^^^^^^^^
  > 14 |       }
       | ^^^^^^^^^^^^^^^^^^
  > 15 |     })
       | ^^^^^^^
    16 |   })
    17 |
    18 |   it('should render text item', () => {

ERROR in test/components/SPortalScreens.spec.ts:26:27
TS2322: Type 'Wrapper<Vue, Element>' is not assignable to type 'Wrapper<object & Record<never, any> & Vue & { $data: Data; $props: Readonly<Partial<{}> & Omit<{ [x: string]: any; }, never>>; $attrs: Data; } & ... 4 more ... & Omit<...>>'.
  Type 'Vue' is not assignable to type 'object & Record<never, any> & Vue & { $data: Data; $props: Readonly<Partial<{}> & Omit<{ [x: string]: any; }, never>>; $attrs: Data; } & ... 5 more ... & Record<...>'.
    Property 'screenName' is missing in type 'Vue' but required in type 'ShallowUnwrapRef<ShallowUnwrapRef<{ screenName: ComputedRef<string | null>; }>>'.
    24 |     const store = new Vuex.Store({ plugins: [Sefirot] })
    25 |
  > 26 |     createWrapper = () => shallowMount(SPortalScreens, { localVue, router, store })
       |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    27 |   })
    28 |
    29 |   it('should open and close screen', async () => {

ERROR in test/components/SScreen.spec.ts:23:27
TS2322: Type 'Wrapper<Vue, Element>' is not assignable to type 'Wrapper<object & Record<never, any> & Vue & { $data: Data; $props: Readonly<Partial<{}> & Omit<{ [x: string]: any; }, never>>; $attrs: Data; } & ... 4 more ... & Omit<...>>'.
  Type 'Vue' is not assignable to type 'object & Record<never, any> & Vue & { $data: Data; $props: Readonly<Partial<{}> & Omit<{ [x: string]: any; }, never>>; $attrs: Data; } & ... 5 more ... & Record<...>'.
    Type 'Vue' is not assignable to type 'Data'.
      Index signature is missing in type 'Vue'.
    21 |     const store = new Vuex.Store({ plugins: [Sefirot] })
    22 |
  > 23 |     createWrapper = () => mount(SScreenMinimal, { localVue, store })
       |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    24 |   })
    25 |
    26 |   it('should open and close screen', async () => {
```

Also, here is the `yarn outdated` after re-installing the deps from this repo. Is this same for you as well? In that case would it be possible to update things like `ts-jest` or `ts-loader`? If anything breaks, and needs further investigation, that would be fine but it would be cool if we can update all excepts for postcss related stuff.

```bash
@nuxtjs/composition-api   0.22.4  0.22.4  0.29.2       devDependencies https://github.com/nuxt-community/composition-api#readme
@nuxtjs/markdownit        1.2.10  1.2.10  2.0.0        devDependencies http://nuxt-community/markdownit-module
@types/body-scroll-lock   2.6.2   2.6.2   3.1.0        devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/body-scroll-lock
@types/jest               26.0.24 26.0.24 27.0.2       devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jest
@types/markdown-it        12.2.2  12.2.3  12.2.3       devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/markdown-it
body-scroll-lock          3.1.5   3.1.5   4.0.0-beta.0 devDependencies https://github.com/willmcpo/body-scroll-lock.git
eslint                    7.32.0  7.32.0  8.0.0        devDependencies https://eslint.org
jest                      26.6.3  26.6.3  27.2.5       devDependencies https://jestjs.io/
markdown-it-anchor        7.1.0   7.1.0   8.3.1        devDependencies https://github.com/valeriangalliat/markdown-it-anchor
postcss-custom-properties 10.0.0  10.0.0  12.0.0       devDependencies https://github.com/postcss/postcss-custom-properties#readme
postcss-nested            4.2.3   4.2.3   5.0.6        devDependencies https://github.com/postcss/postcss-nested#readme
ts-jest                   26.5.6  26.5.6  27.0.5       devDependencies https://kulshekhar.github.io/ts-jest
ts-loader                 8.3.0   8.3.0   9.2.6        devDependencies https://github.com/TypeStrong/ts-loader
```

**Comment by cuebit** [comment]
@kiaking please review the following before merging 👍 

#### Dependencies held back:

**`eslint@7`**
Nuxt currently supports `eslint <= 7`. Can be upgraded once it does, no real evidence of when this will be though.

**`postcss-*`**
Nuxt v2.15+ supports`postcss@8` but requires installing a magnitude of [postcss dependencies](https://github.com/nuxt/nuxt.js/pull/8546) explicitly. Recommend continuing with`postcss@7` until it has a seamless upgrade path.

**`ts-loader@8`**
Nuxt v2 uses `webpack@4` which is not supported by `ts-loader@9` (requires webpack 5+), so there is (and will be) no upgrade path from v8 for the foreseeable future.

**`@nuxtjs/markdownit@1`**
Version 2 is a complete rework of the module but has incomplete types e.g. plugins can only be declared as strings 😕. It doesn't change anything else, for the most part, it would be a pointless/breaking upgrade at this time.

#### Noteworthy changes:

- updated `markdown-it-anchor` to support v8 options.
- added `@vue/vue2-jest` replacing `vue-jest` to support `(ts-)jest@^27`.
- added `testEnvironment` config (`jest >= 27` defaults to `'node'`).
- removed `babelConfig` global (`ts-jest >= 27` defaults to `false`).
- removed component inference in tests, simply won't be supported in Vue 2.

**Comment by kiaking** [comment]
OK this is working like a charm! Well done 👍 👍 👍

**Pull request merged**
