### PR TITLE
feat(medium): add `SContent` component

### PR DESCRIPTION
**Pull request by kiaking**
`<SMedium>` applies basic styles to the native HTML elements. It is similar to `.vp-doc` class on VitePress.

```html
<SMedium>
  <p>Lorem ipsum dolor sit amet.</p>
  <p>Consectetur adipiscing elit.</p>
  <ul>
    <li>Excepteur sint occaecat cupidatat.</li>
    <li>Voluptate velit esse cillum dolore.</li>
    <li>Labore et dolore magna aliqua.</li>
  </ul>
</SMedium>
```

Screenshot 2023-07-12 at 17 51 31

### CODE REVIEW

**Comment by cuebit** [comment]
Medium can mean a lot of things but is mostly associated with (at least for me) the actual website, storage and sizing. This ambiguity makes it more confusing. Considering the use-cases, it's really just a formatter of markdown render text right? What do you think about the following:

- `SFormatted`
- `SFormatText`
- `SStyled`
- `SStyledText`
- `SRenderText`
- `SEnhanced`
- `SEnhancedText`
- `SRichText`

**Comment by kiaking** [comment]
Very good point. Maybe I like `SContent`. I want it to represent a bit more of context. This component style should be applied to where for example documentation in the app. Like we should be able to pass in parsed Markdown to it, and it gets styled properly.

So, name like `SFormatted` or `SStyled` sounds a bit too vague for me 🤔 Because it's styled in a "certain" way, where we should be using this component on quite specific places, not everywhere.

Could it be `SDoc` too... maybe?

@ryo-gk @NozomuIkuta @brc-dd Any ideas? If not I'm kinda toward `SContent` right now 👀

**Comment by brc-dd** [comment]
`SContent` seems fine to me 👀

**Comment by cuebit** [comment]
I think `SContent` sums it up. Also, it reads better in the list of components in the docs and stories than `SMedium` and `SDoc` 👍

**Comment by NozomuIkuta** [comment]
+1 for `SContent`

**Comment by kiaking** [comment]
Rebased and updated `SMedium` -> `SContent`

**Pull request merged**
