### PR TITLE
feat!: prepare for v4

### LINKED ISSUE #424: Sefirot 4 Braking Change List
This is a memo to list possible breaking changes we might make in Sefirot 4. Whether we actually introduce this changes depends on the situation and should be thought through when we actually do the release.

- Remove deprecated old css vars.
- `Table` - Remove deprecated `reset` related options. Should use `actions` instead.
- `Table` - Remove getter support from all cell fields. Rather make `cell` option itself a getter.
- Remove `Data`, `Validation`, and `Form` composable.
- Remove `SSheet` components. Use `SCard` and `SModal`.

### LINKED ISSUE #538: migrate to unplugin-icons
as `iconify-icons` and offline component are no longer maintained

### LINKED ISSUE #541: [Http] Add helper function to check if the error is `FetchError`
When dealing with errors, it would be nice to have a function to assert the error is FetchError so that we can access underlining properties.

```ts
import { isFetchError } from 'sefirot/Http/Http'

const m = useMutation(() => ...)

try {
  m.execute()
} catch (e) {
  if (isFetchError(e)) {
    if (e.data === 'Email already exists') {
      // ...
    }
  }
}
```

### PR DESCRIPTION
**Pull request by brc-dd**
closes #538
closes #424
closes #541

### CODE REVIEW

**Review by kiaking — APPROVED** [review]

**Comment by brc-dd** [comment]
Posting migration guide as comments, please unsubscribe for sanity 😂

**Comment by brc-dd** [comment]
## Change in dependencies:

```diff
-    "@iconify-icons/mdi": "^1.2.48",
-    "@iconify-icons/ph": "^1.2.5",
-    "@iconify-icons/ri": "^1.2.10",
-    "@vitejs/plugin-vue": "^5.0.5",

+    "@iconify-json/mdi": "^1.1.67",
+    "@iconify-json/ph": "^1.1.13",
+    "@iconify-json/ri": "^1.1.21",
```

**Comment by brc-dd** [comment]
## ESM-only

Add `"type": "module"` to client's `package.json` if not already present.

**Comment by brc-dd** [comment]
New base config:

```diff
 import { fileURLToPath } from 'node:url'
+import { defineConfig } from '@globalbrain/sefirot/config/vite'
 import vue from '@vitejs/plugin-vue'
-import { defineConfig, loadEnv } from 'vite'
+import { loadEnv } from 'vite'
 
 export default defineConfig(({ mode }) => {
   const env = loadEnv(mode, process.cwd(), '')
   ...
 
-    optimizeDeps: {
-      include: [
-        ...
-      ]
-    },
-
     resolve: {
       alias: {
-        '@/': fileURLToPath(new URL('./src/', import.meta.url)),
-        'sefirot/': fileURLToPath(new URL('./node_modules/@globalbrain/sefirot/lib/', import.meta.url)),
-        'icons/': fileURLToPath(new URL('./node_modules/@iconify-icons/ph/', import.meta.url)),
-        'icons-mdi/': fileURLToPath(new URL('./node_modules/@iconify-icons/mdi/', import.meta.url)),
-        'icons-ri/': fileURLToPath(new URL('./node_modules/@iconify-icons/ri/', import.meta.url))
-      },
-
-      dedupe: [
-       ...
-      ]
+        '@/': fileURLToPath(new URL('./src/', import.meta.url))
+      }
     },
```

**Comment by brc-dd** [comment]
## removed utils

- `isNullish` -> `== null` / `!= null`
- `isArray` -> `Array.isArray`

**Comment by brc-dd** [comment]
# Removed components

- `SSheet*`

**Comment by brc-dd** [comment]
## Removed composables

- `composables/Data.ts`, `composables/Form.ts`, `composables/Validation.ts` - use `useD`/`useV` instead

**Comment by brc-dd** [comment]
# Added utils

- `isFetchError` (from `http/Http`)

**Comment by brc-dd** [comment]
## Table changes

Rewrite everything if using legacy code 🫠

**Comment by brc-dd** [comment]
## Props changes

- Search for `SActionList` and replace `text` in items to `label`.

**Comment by brc-dd** [comment]
## Stricter types

Some types were lax like this:

```diff
-  unitBefore?: any
-  unitAfter?: any
+  unitBefore?: Component | string
+  unitAfter?: Component | string
```

Might need to adjust props in such cases. Should be picked by vue-tsc.

**Review by kiaking — APPROVED** [review]

**Pull request merged**
